services:
  library:
    build:
      context: .
    env_file:
      - .env

    ports:
      - "8001:8000"
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.17

    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - my_db:/var/lib/postgresql/data

volumes:
  my_db:
